### ISSUE TITLE
client doesn't support sets

### ISSUE THREAD

**Issue by Asuza** [spreaker/nodejs-statsd-client#6]
It looks like the metric type "Set" isn't supported. I was just reading about it here: https://github.com/etsy/statsd/blob/master/docs/metric_types.md

If this repo is still maintained, I don't mind making a PR to add it, but the last update was quite a while ago.

**Comment by pracucci** [comment]
Hi @Asuza thanks for pointing out the missing metric. You're right, "Set" isn't supported. Willing to submit a PR? I will be very happy to merge it.

**Comment by Asuza** [comment]
@pracucci, the PR is ready to go.
